### ISSUE TITLE
[discussion] Git subtree

### ISSUE THREAD

**Issue by imba-tjd** [zthxxx/zthxxx.github.io#1]
> 虽然git 官方推荐是用 subtree 不用 submodule
> https://github.com/zthxxx/zthxxx.github.io/blob/writing/source/_posts/2016-11-02--Git-subtree-Manage-Subpackages-Usage-Summary.md

不知从哪里可以看出来呢？

**Comment by zthxxx** [comment]
文档呀

**Comment by imba-tjd** [comment]
https://www.git-scm.com/doc

reference部分好像直接没有subtree的文档。

Book，在 https://www.git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#_subtree_merge 提了一下subtree，但是没有单独的章节。submodule才有单独的章节。

我只看到了这本书的**第一版**的subtree章节 https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging 的第一句话说了：

```
Now that you’ve seen the difficulties of the submodule system, let’s look at an alternate way to solve the same problem.
```

而这样的话在该书的第二版中不存在。

**Comment by zthxxx** [comment]
@imba-tjd 

感谢你的异议，我也找了一些资料，没有找到 git-scm 官方对两者的明确建议表态

只找到了 [GIT 1.5.2 released](https://lwn.net/Articles/235109/) (2007-05-20) 上发布时新增 subtree 策略，

以及广为流传的 Bitbucket “官方推荐”  [Git subtree: the alternative to Git submodule](https://www.atlassian.com/git/tutorials/git-subtree) (2013-05)

以及一些 git 官方对两者的比较  [Comparing 'subtree' merge with submodules]( https://github.com/git/git/blob/master/Documentation/howto/using-merge-subtree.txt#L51)

综上我猜测广为流程的 "官方推荐" 说法只是一种误导，起来源可能是是因为 git/bitbucket 官方写了很多 subtree 对与 submodule 的优点，但没有反过来的比较

最后你说的没有 subtree 的单独章节，

因为 `subtree` 只是 merge 的一种策略模式，并非一个单独的命令，而 `git subtree` 只是 `git merge -s subtree` 的 alias；

并且他们可能[忘了给 subtree 生成单独页面](https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.4.3.txt#L43)
